-- basic_analysis.trips_by_areas

-- Compare run trip stats for each area (such as LH Stuttgart)

-- @author dwedekind

-- Aggregate trips in the base case simulation run by area and mode
WITH TRIP_STATS_BC AS
	(SELECT SIM_TRIPS_ENRICHED_BC.RUN_NAME,
			SIM_TRIPS_ENRICHED_BC.AREA,
			SIM_TRIPS_ENRICHED_BC.MATSIM_CAL_MAIN_MODE,
			COUNT(SIM_TRIPS_ENRICHED_BC.TRIP_ID) AS TRIPS_BC,
			((COUNT(SIM_TRIPS_ENRICHED_BC.TRIP_ID))::numeric / SUM(COUNT(SIM_TRIPS_ENRICHED_BC.TRIP_ID)) OVER (PARTITION BY SIM_TRIPS_ENRICHED_BC.RUN_NAME)) AS MODE_SHARE_BC
		FROM MATSIM_OUTPUT.SIM_TRIPS_ENRICHED_BC
	 
	 	-- Limit analysis to agents living in 'Region Stuttgart'
		WHERE (SUBPOP = 'region_stuttgart'::text)
	 
		GROUP BY SIM_TRIPS_ENRICHED_BC.RUN_NAME,
			SIM_TRIPS_ENRICHED_BC.AREA,
			SIM_TRIPS_ENRICHED_BC.MATSIM_CAL_MAIN_MODE),
			
			
	-- Aggregate trips in the measure simulation runs by area and mode		
	TRIP_STATS_MEASURES AS
	(SELECT SIM_TRIPS_ENRICHED_MEASURES.RUN_NAME,
			SIM_TRIPS_ENRICHED_MEASURES.AREA,
			SIM_TRIPS_ENRICHED_MEASURES.MATSIM_CAL_MAIN_MODE,
			COUNT(SIM_TRIPS_ENRICHED_MEASURES.TRIP_ID) AS TRIPS_M,
			((COUNT(SIM_TRIPS_ENRICHED_MEASURES.TRIP_ID))::numeric / SUM(COUNT(SIM_TRIPS_ENRICHED_MEASURES.TRIP_ID)) OVER (PARTITION BY SIM_TRIPS_ENRICHED_MEASURES.RUN_NAME)) AS MODE_SHARE_M
		FROM MATSIM_OUTPUT.SIM_TRIPS_ENRICHED_MEASURES
	 
	 	-- Limit analysis to agents living in 'Region Stuttgart'
		WHERE (SUBPOP = 'region_stuttgart'::text)
	 
		GROUP BY SIM_TRIPS_ENRICHED_MEASURES.RUN_NAME,
			SIM_TRIPS_ENRICHED_MEASURES.AREA,
			SIM_TRIPS_ENRICHED_MEASURES.MATSIM_CAL_MAIN_MODE)
			

-- Join base case numbers to each run numbers for direct comparison/ visualization
SELECT M.RUN_NAME,
	BC.AREA,
	BC.MATSIM_CAL_MAIN_MODE,
	BC.TRIPS_BC,
	BC.MODE_SHARE_BC,
	M.TRIPS_M,
	M.MODE_SHARE_M,
	(M.TRIPS_M - BC.TRIPS_BC) AS TRIPS_DIFF,
	(M.MODE_SHARE_M - BC.MODE_SHARE_BC) AS MODE_SHARE_DIFF
FROM (TRIP_STATS_BC BC JOIN TRIP_STATS_MEASURES M ON (((BC.MATSIM_CAL_MAIN_MODE = M.MATSIM_CAL_MAIN_MODE) AND (BC.AREA = M.AREA))))
ORDER BY M.RUN_NAME,
	BC.AREA,
	BC.MATSIM_CAL_MAIN_MODE