-- basic_analysis.trips_by_mode_rel

-- Compare trip stats for each trip relation per run and mode
-- Trip stats are number of trips, mode share, average trip distance and average trip duration
-- Relations are LK Boeblingen - LK Esslingen and between focus areas of Boeblingen and Esslingen

-- @author dwedekind

-- Aggregate trips between Boeblingen and Esslingen
WITH BOEB_ESSL AS
	(SELECT SIM_TRIPS_ENRICHED.RUN_NAME,
			CASE 
	 			WHEN SIM_TRIPS_ENRICHED.REL_BOEBL_ESSL = 1 THEN 'LK Boeb - LK Essl'
	 			ELSE 'Außer LK Boeb - LK Essl'
	 		END AS RES_GROUP,
			COUNT(SIM_TRIPS_ENRICHED.TRIP_ID) AS TRIPS,
			AVG(SIM_TRIPS_ENRICHED.TRAVELED_DISTANCE) AVG_TRIP_DIST,
	 		AVG(SIM_TRIPS_ENRICHED.TRAV_TIME) AVG_TRIP_DUR
		FROM MATSIM_OUTPUT.SIM_TRIPS_ENRICHED
		GROUP BY SIM_TRIPS_ENRICHED.RUN_NAME,
			SIM_TRIPS_ENRICHED.REL_BOEBL_ESSL),
			
			
-- Aggregate trips for trips between focus areas of Boeblingen and Esslingen county
FOCUS_AREAS AS
	(SELECT SIM_TRIPS_ENRICHED.RUN_NAME,
			CASE 
	 			WHEN SIM_TRIPS_ENRICHED.REL_FOCUS_AREAS = 1 THEN 'Fokusrelationen'
	 			ELSE 'Außer Fokusrelationen'
	 		END AS RES_GROUP,
			COUNT(SIM_TRIPS_ENRICHED.TRIP_ID) AS TRIPS,
			AVG(SIM_TRIPS_ENRICHED.TRAVELED_DISTANCE) AVG_TRIP_DIST,
	 		AVG(SIM_TRIPS_ENRICHED.TRAV_TIME) AVG_TRIP_DUR
		FROM MATSIM_OUTPUT.SIM_TRIPS_ENRICHED
		GROUP BY SIM_TRIPS_ENRICHED.RUN_NAME,
			SIM_TRIPS_ENRICHED.REL_FOCUS_AREAS),
			
			
-- Union measure groups
M_GROUPS AS (
	SELECT * FROM (			
		SELECT * FROM BOEB_ESSL
		UNION
		SELECT * FROM FOCUS_AREAS
	) AS UN

	ORDER BY RUN_NAME, RES_GROUP
)


-- Build final table
-- Calculate diffs and changes
SELECT
	M.RUN_NAME,
	M.RES_GROUP,
	BC.TRIPS TRIPS_BC,
	M.TRIPS TRIPS_M,
	(M.TRIPS - BC.TRIPS) AS TRIPS_DIFF,
	(M.TRIPS - BC.TRIPS)/BC.TRIPS::FLOAT AS TRIPS_CHANGE,
	BC.AVG_TRIP_DIST BC_AVG_TRIP_DIST,
	M.AVG_TRIP_DIST M_AVG_TRIP_DIST,
	(M.AVG_TRIP_DIST - BC.AVG_TRIP_DIST) AS AVG_TRIP_DIST_DIFF,
	(M.AVG_TRIP_DIST - BC.AVG_TRIP_DIST)/BC.AVG_TRIP_DIST::FLOAT AS AVG_TRIP_DIST_CHANGE,
	BC.AVG_TRIP_DUR BC_AVG_TRIP_DUR,
	M.AVG_TRIP_DUR M_AVG_TRIP_DUR,
	(M.AVG_TRIP_DUR - BC.AVG_TRIP_DUR) AS AVG_TRIP_DUR_DIFF,
	(M.AVG_TRIP_DUR - BC.AVG_TRIP_DUR)/BC.AVG_TRIP_DUR::FLOAT AS AVG_TRIP_DUR_CHANGE
	
FROM M_GROUPS M
LEFT JOIN M_GROUPS BC
ON BC.RES_GROUP = M.RES_GROUP
WHERE BC.RUN_NAME = 'bc'