-- basic_analysis.trips_on_relation

-- Compare run trip stats on relation

-- @author dwedekind

-- Aggregate trips in the base case simulation run by area and mode
WITH TRIP_STATS_BC AS
	(SELECT SIM_TRIPS_ENRICHED_BC.RUN_NAME,
			SIM_TRIPS_ENRICHED_BC.MATSIM_CAL_MAIN_MODE,
			COUNT(SIM_TRIPS_ENRICHED_BC.TRIP_ID) AS TRIPS_BC,
			((COUNT(SIM_TRIPS_ENRICHED_BC.TRIP_ID))::numeric / SUM(COUNT(SIM_TRIPS_ENRICHED_BC.TRIP_ID)) OVER (PARTITION BY SIM_TRIPS_ENRICHED_BC.RUN_NAME)) AS MODE_SHARE_BC
		
	 	FROM MATSIM_OUTPUT.SIM_TRIPS_ENRICHED_BC
	 
	 	-- Limit to trips on Boeblingen-Esslingen county relation
	 	-- At this place, all agents trips (not only those of living in 'Region Stuttgart' are considered)
		WHERE (START_KREIS_AGS = '08115'
									AND END_KREIS_AGS = '08116')
			OR (START_KREIS_AGS = '08116'
							AND END_KREIS_AGS = '08115')
	 
		GROUP BY SIM_TRIPS_ENRICHED_BC.RUN_NAME,
			SIM_TRIPS_ENRICHED_BC.MATSIM_CAL_MAIN_MODE),
	TRIP_STATS_MEASURES AS
	
	-- Aggregate trips in the measure simulation runs by area and mode
	-- At this place, all agents trips (not only those of living in 'Region Stuttgart' are considered)
	(SELECT SIM_TRIPS_ENRICHED_MEASURES.RUN_NAME,
			SIM_TRIPS_ENRICHED_MEASURES.MATSIM_CAL_MAIN_MODE,
			COUNT(SIM_TRIPS_ENRICHED_MEASURES.TRIP_ID) AS TRIPS_M,
			((COUNT(SIM_TRIPS_ENRICHED_MEASURES.TRIP_ID))::numeric / SUM(COUNT(SIM_TRIPS_ENRICHED_MEASURES.TRIP_ID)) OVER (PARTITION BY SIM_TRIPS_ENRICHED_MEASURES.RUN_NAME)) AS MODE_SHARE_M
		
	 	FROM MATSIM_OUTPUT.SIM_TRIPS_ENRICHED_MEASURES
	 
	 	-- Limit to trips on Boeblingen-Esslingen county relation
		WHERE (START_KREIS_AGS = '08115'
									AND END_KREIS_AGS = '08116')
			OR (START_KREIS_AGS = '08116'
							AND END_KREIS_AGS = '08115')
	 
		GROUP BY SIM_TRIPS_ENRICHED_MEASURES.RUN_NAME,
			SIM_TRIPS_ENRICHED_MEASURES.MATSIM_CAL_MAIN_MODE)
			
			
SELECT M.RUN_NAME,
	BC.MATSIM_CAL_MAIN_MODE,
	BC.TRIPS_BC,
	BC.MODE_SHARE_BC,
	M.TRIPS_M,
	M.MODE_SHARE_M,
	(M.TRIPS_M - BC.TRIPS_BC) AS TRIPS_DIFF,
	(M.MODE_SHARE_M - BC.MODE_SHARE_BC) AS MODE_SHARE_DIFF
FROM (TRIP_STATS_BC BC JOIN TRIP_STATS_MEASURES M ON (BC.MATSIM_CAL_MAIN_MODE = M.MATSIM_CAL_MAIN_MODE))
ORDER BY M.RUN_NAME,
	BC.MATSIM_CAL_MAIN_MODE