-- pt_analysis.transfer_statistics

-- Count access, egress and number of transfers at per stop
 
-- @author dwedekind

 
-- Select trips that have pt legs ending at Stuttgart-Rohr
WITH FST AS(
	SELECT L.*,
		SPLIT_PART(ACCESS_STOP_ID,'.',1) ACCESS_STOP_GROUP,
		SPLIT_PART(EGRESS_STOP_ID,'.',1) EGRESS_STOP_GROUP
	FROM MATSIM_OUTPUT.SIM_LEGS_RAW L
),


-- Select legs of pt trips only
PT_TRIP_LEGS AS(
	SELECT L.*,
	CASE
		WHEN MODE = 'pt' THEN 1
		ELSE 0
	END AS PT_MODE
	FROM MATSIM_OUTPUT.SIM_TRIPS_ENRICHED T
	LEFT JOIN MATSIM_OUTPUT.SIM_LEGS_RAW L
	ON T.RUN_NAME = L.RUN_NAME
	AND T.TRIP_ID = L.TRIP_ID
	WHERE T.MATSIM_CAL_MAIN_MODE = 'pt'
)

-- Left side of transfer
SELECT FOO.*,
	CASE
		WHEN (PT_LEAD_1_MODE+PT_LEAD_2_MODE+PT_LEAD_3_MODE) > 0 THEN 1
		ELSE 0
	END AS PT_LEADS
FROM(
	SELECT P.*,
		LEAD(PT_MODE, 1) OVER (PARTITION BY RUN_NAME, TRIP_ID ORDER BY DEP_TIME) PT_LEAD_1_MODE,
		LEAD(PT_MODE, 2) OVER (PARTITION BY RUN_NAME, TRIP_ID ORDER BY DEP_TIME) PT_LEAD_2_MODE,
		LEAD(PT_MODE, 3) OVER (PARTITION BY RUN_NAME, TRIP_ID ORDER BY DEP_TIME) PT_LEAD_3_MODE
	FROM PT_TRIP_LEGS P
) FOO

