-- br_analysis.stop_feed_buffers

-- Create stop feed buffers
 
-- @author dwedekind

WITH FEED_FIG AS(
	SELECT
		RUN_NAME,
		((2765/4.0579732)*SPEED_VALUE)/BEELINE_DFACTOR::float AS FEED_RADIUS,
		(2765/4.0579732) FEED_DUR
	FROM MATSIM_OUTPUT.BIKE_SPEED
),

SINGLE_BUFFERS AS 
(
	SELECT
		SF.RUN_NAME,
		SF.ID,
		SF.NAME,
		G.AGS,
		G.GEN,
		SF.GEOMETRY SF_POINT,
		F.FEED_RADIUS,
		F.FEED_DUR,
		ST_BUFFER(SF.GEOMETRY, F.FEED_RADIUS) SF_CIRCLE
	FROM MATSIM_OUTPUT.STOP_FACILITIES AS SF
	LEFT JOIN FEED_FIG F
	ON SF.RUN_NAME = F.RUN_NAME
	LEFT JOIN RAW.GEMEINDEN G
	ON ST_WITHIN(SF.GEOMETRY, G.GEOMETRY)
	WHERE SF.VVS_BIKE_RIDE = 'true'
	AND G.AGS IN ('08115003', '08115045', '08116077', '08116078')
)

SELECT
	RUN_NAME,
	ST_UNION(SF_CIRCLE) AS SF_BUFFERS
FROM SINGLE_BUFFERS
GROUP BY RUN_NAME
