WITH S60_TRAVELERS AS (
	SELECT RUN_NAME,
		"personId"
	FROM MATSIM_OUTPUT.PERSON_2_LINK_LIST
	WHERE "linkId" IN ('trNew0001', 'trNew0002')
	GROUP BY RUN_NAME,
		"personId"
),

S60_TRAVELERS_ON_LINKS AS (
	SELECT L.*,
		(SPLIT_PART(L.TIME,':',1)::bigint * 24 * 60 + SPLIT_PART(L.TIME,':',2)::bigint * 60 + SPLIT_PART(L.TIME,':',3)::bigint) TM
	FROM S60_TRAVELERS S60
	LEFT JOIN MATSIM_OUTPUT.PERSON_2_LINK_LIST L
	ON S60.RUN_NAME = L.RUN_NAME
	AND S60."personId" = L."personId"
),

S60_TRAVELERS_TRIPS AS(
	SELECT L.*,
		T.TRIP_ID,
		T.DEP_TIME,
		(T.DEP_TIME + T.TRAV_TIME) ARR_TIME
	FROM S60_TRAVELERS_ON_LINKS L
	LEFT JOIN MATSIM_OUTPUT.SIM_TRIPS_ENRICHED T
	ON L.RUN_NAME = T.RUN_NAME
	AND L."personId" = T.PERSON
	AND L.MODE = T.MATSIM_CAL_MAIN_MODE
	WHERE L.TM >= T.DEP_TIME AND L.TM <= (T.DEP_TIME + T.TRAV_TIME)
)

SELECT * FROM S60_TRAVELERS_TRIPS
WHERE RUN_NAME = 'm5_3'
AND TRIP_ID = '73733060_893_1'
ORDER BY TM