-- basic_analysis.trip_figures

-- Provide basic figures of 
 
-- @author dwedekind


-- Collect stats of base case
WITH BC AS(
	SELECT RUN_NAME,
		MATSIM_CAL_MAIN_MODE,
		COUNT(TRIP_ID) TRIPS,
		COUNT(TRIP_ID) / SUM(COUNT(TRIP_ID)) OVER (PARTITION BY RUN_NAME) MODE_SHARE
	FROM MATSIM_OUTPUT.SIM_TRIPS_ENRICHED_BC
	GROUP BY RUN_NAME, MATSIM_CAL_MAIN_MODE
	
),

-- Collect stats of measures
M AS (
	SELECT RUN_NAME,
		MATSIM_CAL_MAIN_MODE,
		COUNT(TRIP_ID) TRIPS,
		COUNT(TRIP_ID) / SUM(COUNT(TRIP_ID)) OVER (PARTITION BY RUN_NAME) MODE_SHARE
	FROM MATSIM_OUTPUT.SIM_TRIPS_ENRICHED_MEASURES
	GROUP BY RUN_NAME, MATSIM_CAL_MAIN_MODE
)


-- Join
SELECT
	M.RUN_NAME,
	M.MATSIM_CAL_MAIN_MODE,
	BC.TRIPS BC_TRIPS,
	M.TRIPS M_TRIPS,
	((M.TRIPS - BC.TRIPS)::FLOAT / BC.TRIPS) TRIPS_DEVIATION,
	BC.MODE_SHARE BC_MODE_SHARE,
	M.MODE_SHARE M_MODE_SHARE,
	((M.MODE_SHARE - BC.MODE_SHARE)::FLOAT / BC.MODE_SHARE) MODE_SHARE_DEVIATION
FROM M
JOIN BC
ON BC.MATSIM_CAL_MAIN_MODE = M.MATSIM_CAL_MAIN_MODE





