-- matsim_output.sim_trips_enriched

-- Enrich the trip.csv output with some person attributes and distance groups

-- @author dwedekind

SELECT T.*
	
	-- Add home properties for each agent's trip
	,H.KRS_AGS AGENT_HOME_KRS_AGS
	,H.KRS_GEN AGENT_HOME_KRS_GEN
	,H.GEM_AGS AGENT_HOME_GEM_AGS
	,H.GEM_GEN AGENT_HOME_GEM_GEN
	,H.REGIOSTAR7
	,H.SUBPOP
	,H.CALIB_GROUP AREA
	
	-- Assign distance group and distance group no to each trip based on euclidean trip distance
	,CASE 
		WHEN (
				T.EUCLIDEAN_DISTANCE < 500
				)
			THEN 'unter_500m'::TEXT
		WHEN (
				(T.EUCLIDEAN_DISTANCE >= 500)
				AND (T.EUCLIDEAN_DISTANCE < 1000)
				)
			THEN '500m_bis_1km'::TEXT
		WHEN (
				(T.EUCLIDEAN_DISTANCE >= 1000)
				AND (T.EUCLIDEAN_DISTANCE < 2000)
				)
			THEN '1km_bis_2km'::TEXT
		WHEN (
				(T.EUCLIDEAN_DISTANCE >= 2000)
				AND (T.EUCLIDEAN_DISTANCE < 5000)
				)
			THEN '2km_bis_5km'::TEXT
		WHEN (
				(T.EUCLIDEAN_DISTANCE >= 5000)
				AND (T.EUCLIDEAN_DISTANCE < 10000)
				)
			THEN '5km_bis_10km'::TEXT
		WHEN (
				(T.EUCLIDEAN_DISTANCE >= 10000)
				AND (T.EUCLIDEAN_DISTANCE < 20000)
				)
			THEN '10km_bis_20km'::TEXT
		WHEN (
				(T.EUCLIDEAN_DISTANCE >= 20000)
				AND (T.EUCLIDEAN_DISTANCE < 50000)
				)
			THEN '20km_bis_50km'::TEXT
		WHEN (
				(T.EUCLIDEAN_DISTANCE >= 50000)
				AND (T.EUCLIDEAN_DISTANCE < 100000)
				)
			THEN '50km_bis_100km'::TEXT
		ELSE 'ueber_100km'::TEXT
		END AS DISTANCE_GROUP
	,CASE 
		WHEN (
				T.EUCLIDEAN_DISTANCE < 500
				)
			THEN 1
		WHEN (
				(T.EUCLIDEAN_DISTANCE >= 500)
				AND (T.EUCLIDEAN_DISTANCE < 1000)
				)
			THEN 2
		WHEN (
				(T.EUCLIDEAN_DISTANCE >= 1000)
				AND (T.EUCLIDEAN_DISTANCE < 2000)
				)
			THEN 3
		WHEN (
				(T.EUCLIDEAN_DISTANCE >= 2000)
				AND (T.EUCLIDEAN_DISTANCE < 5000)
				)
			THEN 4
		WHEN (
				(T.EUCLIDEAN_DISTANCE >= 5000)
				AND (T.EUCLIDEAN_DISTANCE < 10000)
				)
			THEN 5
		WHEN (
				(T.EUCLIDEAN_DISTANCE >= 10000)
				AND (T.EUCLIDEAN_DISTANCE < 20000)
				)
			THEN 6
		WHEN (
				(T.EUCLIDEAN_DISTANCE >= 20000)
				AND (T.EUCLIDEAN_DISTANCE < 50000)
				)
			THEN 7
		WHEN (
				(T.EUCLIDEAN_DISTANCE >= 50000)
				AND (T.EUCLIDEAN_DISTANCE < 100000)
				)
			THEN 8
		ELSE 9
		END AS DISTANCE_GROUP_NO
FROM (
	MATSIM_INPUT.SIM_AGENTS_ENRICHED H JOIN MATSIM_OUTPUT.SIM_TRIPS_RAW T ON ((H.PERSON_ID = T.PERSON))
	)
