-- cal.mid_trip_stats_stuttgart_rebased

-- Aggregate rebased Stuttgart mid trips by mode to construct rebased overall Stuttgart Mid Values
-- Join original Stuttgart Mid values (which cannot be met due to missing trips in Senozon model)

-- @author dwedekind

WITH REBASED
AS (
	SELECT RUN_NAME
		,AREA
		,MATSIM_MAIN_MODE
		,SUM(MID_TRIPS_ABS_REBASED) MID_TRIPS_ABS_REBASED
		,(SUM(MID_TRIPS_ABS_REBASED) / SUM(SUM(MID_TRIPS_ABS_REBASED)) OVER (PARTITION BY RUN_NAME)) MID_MODE_SHARE_REBASED
	FROM CAL.MID_TRIP_STATS_BY_MODE_DISTANCE_STUTTGART_REBASED
	
	GROUP BY RUN_NAME
		,AREA
		,MATSIM_MAIN_MODE
	ORDER BY RUN_NAME
		,AREA
		,MATSIM_MAIN_MODE
	)
	
SELECT REB.RUN_NAME
	,REB.AREA
	,REB.MATSIM_MAIN_MODE
	,CAL.MID_TRIPS_ABS
	,REB.MID_TRIPS_ABS_REBASED
	,CAL.MID_MODE_SHARE / 100 MID_MODE_SHARE
	,REB.MID_MODE_SHARE_REBASED
	
FROM REBASED REB
INNER JOIN CAL.MID_TRIP_STATS_MULTIPLE_LEVEL CAL ON CAL.AREA = REB.AREA
	AND CAL.MATSIM_MAIN_MODE = REB.MATSIM_MAIN_MODE
