-- cmp.cmp_trip_stats_stuttgart

-- Compare simulation trip stats to mid values (Stuttgart overall values)

-- @author dwedekind

SELECT CAL.RUN_NAME,
	CAL.AREA,
	CAL.MATSIM_MAIN_MODE,
	SIM.SIM_TRIPS_ABS_SCALED_100,
	CAL.MID_TRIPS_ABS,
	CAL.MID_TRIPS_ABS_REBASED,
	SIM.SIM_MODE_SHARE,
	CAL.MID_MODE_SHARE,
	CAL.MID_MODE_SHARE_REBASED
	
FROM MATSIM_OUTPUT.SIM_TRIP_STATS SIM
INNER JOIN CAL.MID_TRIP_STATS_STUTTGART_REBASED CAL ON SIM.RUN_NAME = CAL.RUN_NAME
AND SIM.AREA = CAL.AREA
AND SIM.MATSIM_MAIN_MODE = CAL.MATSIM_MAIN_MODE